
import React from 'react';
import { MarketResearchReport, SolicitationStatus } from '../../types';
import { Landmark, ArrowUpRight, Search, ShieldCheck, Factory, TrendingUp } from 'lucide-react';
import { formatCurrency } from '../../utils/formatting';

interface Props {
    report: MarketResearchReport;
    onAdvance: () => void;
    status: SolicitationStatus;
}

const MarketResearchModule: React.FC<Props> = ({ report, onAdvance, status }) => {
    return (
        <div className="bg-white border border-zinc-200 rounded-2xl overflow-hidden shadow-sm animate-in slide-in-from-bottom-2">
            <div className="p-4 border-b border-zinc-100 bg-zinc-900 text-white flex justify-between items-center">
                <div className="flex items-center gap-3">
                    <Search size={16} className="text-rose-500" />
                    <h4 className="text-xs font-bold uppercase tracking-widest">Market Research Intelligence</h4>
                </div>
                <div className="flex items-center gap-4">
                    <span className="text-[10px] font-bold text-zinc-400 uppercase">Set-Aside Candidate</span>
                    <div className={`h-2.5 w-10 rounded-full bg-zinc-800 p-0.5 flex ${report.smallBusinessSetAside ? 'justify-end' : 'justify-start'}`}>
                        <div className={`h-full aspect-square rounded-full ${report.smallBusinessSetAside ? 'bg-emerald-500' : 'bg-zinc-600'}`} />
                    </div>
                </div>
            </div>
            
            <div className="p-6 grid grid-cols-1 md:grid-cols-3 gap-8">
                {/* Core Analytics */}
                <div className="space-y-6">
                    <div className="p-4 bg-zinc-50 rounded-xl border border-zinc-100">
                        <p className="text-[9px] font-bold text-zinc-400 uppercase tracking-widest mb-1">Recommended NAICS</p>
                        <div className="flex items-baseline gap-2">
                            <span className="text-lg font-mono font-bold text-zinc-900">{report.naicsCode}</span>
                            <span className="text-[10px] text-zinc-500">Eng Services</span>
                        </div>
                    </div>
                    <div className="p-4 bg-zinc-50 rounded-xl border border-zinc-100">
                        <p className="text-[9px] font-bold text-zinc-400 uppercase tracking-widest mb-1">IGCE Estimate</p>
                        <p className="text-lg font-mono font-bold text-rose-700">{formatCurrency(report.estimatedMarketPrice)}</p>
                    </div>
                    <div className="p-4 bg-zinc-50 rounded-xl border border-zinc-100">
                        <p className="text-[9px] font-bold text-zinc-400 uppercase tracking-widest mb-3">Small Biz Strategy</p>
                        <div className="space-y-2">
                            <div className="flex justify-between items-center text-xs">
                                <span className="text-zinc-500">8(a) Program</span>
                                <ShieldCheck size={12} className="text-emerald-500"/>
                            </div>
                            <div className="flex justify-between items-center text-xs">
                                <span className="text-zinc-500">HUBZone</span>
                                <ShieldCheck size={12} className="text-zinc-300"/>
                            </div>
                            <div className="flex justify-between items-center text-xs">
                                <span className="text-zinc-500">SDVOSB</span>
                                <ShieldCheck size={12} className="text-emerald-500"/>
                            </div>
                        </div>
                    </div>
                </div>

                {/* AI Analysis Narrative */}
                <div className="md:col-span-2 space-y-6">
                    <div className="bg-rose-50/30 border border-rose-100 rounded-2xl p-6 relative">
                        <div className="absolute top-4 right-4 p-2 bg-white rounded-lg shadow-sm border border-rose-100">
                            <TrendingUp size={16} className="text-rose-600" />
                        </div>
                        <h5 className="text-sm font-bold text-zinc-900 mb-3 flex items-center gap-2">
                            <Factory size={16} className="text-rose-600" /> Sector Analysis & Competitors
                        </h5>
                        <div className="text-sm text-zinc-700 leading-relaxed space-y-4 mb-6">
                            {report.aiNarrative ? (
                                <div className="whitespace-pre-wrap">{report.aiNarrative}</div>
                            ) : (
                                <p className="italic text-zinc-400">Market intelligence report generated by Sentinel-3 Engine...</p>
                            )}
                        </div>
                        <div className="grid grid-cols-2 gap-4">
                            {report.competitors.map(c => (
                                <div key={c} className="bg-white px-3 py-2 rounded-lg border border-rose-100 text-[10px] font-bold text-rose-700 flex justify-between items-center">
                                    {c} <ArrowUpRight size={10} />
                                </div>
                            ))}
                        </div>
                    </div>

                    {status === 'Market Research' && (
                        <div className="flex justify-end pt-4 border-t border-zinc-100">
                             <button 
                                onClick={onAdvance}
                                className="flex items-center gap-2 px-6 py-2.5 bg-zinc-900 text-white rounded-xl text-[10px] font-bold uppercase tracking-widest hover:bg-zinc-800 transition-all shadow-lg"
                             >
                                Finalize Research & Issue RFP <ArrowUpRight size={14}/>
                             </button>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
};

export default MarketResearchModule;
