
// --- FMR Volume 12, Chapter 23 Content ---
export const FMR_V12_CH23_CONTENT = `
6.6 Working Capital Fund Priorities (230606)
In order to ensure that the cash reserves of any Working Capital Fund activity are used for the highest priority requirements, the commander of the Working Capital Fund activity shall notify the Principal Deputy Under Secretary of Defense (Comptroller), in writing, and wait 5 workdays before filling the unfunded customer order.

6.7 Guidance on Reporting (230607)
As needed, the OUSD(C) will provide additional guidance on reporting the use of this authority for designated operations that become eligible for the special funding mechanisms available under 10 U.S.C. 127a.

7.0 COST COLLECTION (2307)
7.1 Special Program Codes (230701)
Upon being alerted of an impending contingency operation, each participating DoD Component shall establish a unique special program code to capture costs. The OUSD(C) Operations Directorate shall issue a Standard Financial Information Structure (SFIS) code for contingency operations. The SFIS Values Library Service webpage maintains a list of contingency codes. Additionally, the Joint Staff shall issue a three-digit CJCS Project Code, which provides precedence for supply requisitions and facilitates cost capturing and reporting.
7.2 Accounting System(s) (230702)
Each organization that supports a contingency operation shall capture related obligations and disbursements in its accounting system(s) at the lowest possible level of the organization. This provides tracking of obligations and disbursements for affected appropriations.
7.3 Costs Related to Contingency Operations (230703)
Costs related to a contingency operation may be incurred both in the area of responsibility and in other locations. It is the responsibility of the organization that incurs costs in support of the operation, directly or indirectly, to ensure that information on all costs is transmitted to the appropriate DoD Component Senior Financial Manager for forwarding to DFAS, as appropriate.
7.4 Cost Accounting Systems (230704)
Cost accounting systems shall not be established solely for the purpose of determining costs for contingency operations, but the data from existing systems shall be used as applicable.
7.5 Incremental and Billable Costs (230705)
DoD Component Senior Financial Managers shall determine incremental and billable costs.

8.0 COST REPORTING (2308)
8.1 Cost Reporting Requirements (230801)
Cost reports, SFs 1080, and substantiating documents shall be submitted through the DoD Component Senior Financial Manager to DFAS. Component submissions shall be initiated in sufficient time to arrive at DFAS not later than 30 days following the month in which the cost occurs. Costs shall be reported only by the DoD Component Senior Financial Manager that incurs the cost against appropriated funds. Submissions to DFAS for reporting and billing shall be approved by the DoD Component Senior Financial Manager. See Annex 1 for the standard data reporting format for preparation of the Contingency Cost Report.
8.2 DoD Component Inclusions (230802)
The DoD Component cost reports shall include all costs, including Working Capital Funds costs (common user/Component unique), that are collected in the accounting or cost accounting system. The Services shall reimburse the Working Capital Funds activity for costs, and separately reflect such costs in their cost reports.
8.3 Monthly Consolidation Cost Reports (230803)
On a monthly basis, DFAS will consolidate the costs reported provided by the DoD Components and provide reports to the offices of the OUSD (Comptroller), Component Command comptrollers, DoD Component Senior Financial Managers and others, as required, no later than 15 days after receipt from the DoD Components.

9.0 DETERMINING COST (2309)
9.1 Baseline Costs (230901)
Baseline costs are the continuing annual costs of DoD operations funded by the operation and maintenance and military personnel appropriations. Essentially, baseline costs are those costs that would be incurred whether or not a contingency operation took place, i.e., programmed and budgeted costs. Examples include: scheduled flying hours, steaming days, training days, and exercises.
9.2 Incremental Costs (230902)
Incremental costs are additional costs to the DoD Component appropriations that would not have been incurred had the contingency operation not been supported... The following are examples of allowable incremental costs:
9.2.1. Military entitlements such as premium pay, hazardous duty pay, family separation allowance, or other payments made over and above the normal monthly payroll costs.
9.2.2. Increases in the amount of allowances due to changes in geographic assignment area due to a contingency (i.e., Basic Allowance for Subsistence (BAS) or Basic Allowance for Housing (BAH)).
9.2.3. Travel and per diem of active military personnel and costs of Reserve Component personnel, called to active duty by a federal official, who are assigned solely to support the contingency.
9.2.4. Overtime, travel, and per diem of permanent DoD civilian personnel in support of a contingency.
9.2.5. Wages, travel, and per diem of temporary DoD civilian personnel hired or assigned solely to perform services supporting the operation.
9.2.6. Transportation costs of moving personnel, material, equipment, and supplies to the contingency or contingency staging area, including such things as port handling charges; packing, crating and handling charges; first and second destination charges.
9.2.7. Cost of rents, communications, and utilities that is attributable to the contingency. Examples of such incremental costs include: telephone service, computer time, satellite time, and crypto-traffic support of the contingency.
9.2.8. Cost of work, services, training, and material procured under contract for the specific purpose of providing assistance in a contingency.
9.2.9. Cost of material, equipment, and supplies from regular stocks used in providing directed assistance...
9.2.10. Costs incurred that are paid from trust, revolving, or other funds, and whose reimbursement is required.
9.2.11. Replacement costs of attrition losses directly attributable to support of the operation.
9.2.12. That portion of equipment overhaul and maintenance costs when computed on a fractional use basis when the additive cost attributable to the contingency can be identified.
9.2.13. Cost of increased flying hours in excess of the level of flying hours otherwise programmed and budgeted for...
9.2.14. Service specific costs for increased OPTEMPO, such as steaming costs for the Navy...
9.3 Cost Offsets (230903)
In some instances, costs for which funds have been appropriated may not be incurred as result of a contingency operation. Examples include: basic allowance for subsistence not paid, training not conducted, and base operations support not provided... These offsets shall be accurately documented and reported...
`;

export const FMR_V11B_CH3_CONTENT = `
3.3 Revenue Billings (110303)
3.3.1. The customer funding an order must be billed for the revenue recognized by the DWCF activity performing the order. When advance payments are received, those advances must be reclassified to the appropriate revenue account when the revenue is earned. Revenue billings to customers must reflect due credit for the advances received. In no case must the total amount of revenue recognized and billed by the DWCF activity exceed the amount of the order. The DWCF customer must not incur obligations for supplies or services ordered from a DWCF activity that exceed the amount of appropriations or other funds available for such purposes. See 10 U.S.C. § 2208 (f).
3.3.2. Revenue billings must be accomplished at least monthly including applicable labor, material, overhead, and surcharges as well as the value of material in inventory that is identified and held in reserve for specific orders, and amounts of work-in-process in contractors’ plants and other government plants that are identified to specific orders. These billings should be made as late as possible in the month so that they include these items to the maximum extent possible and still permit the orderly processing of the collection in the same month. Every effort must be made to reduce the billing and collection lag so that a greater portion of the costs is recovered in the month incurred.

*3.4 Accounting for Reimbursements and Revenue Recognition (110304)
The DoD Standard Reporting Chart of Accounts provides the DoD account definitions and determines how they are to be used. The DoD USSGL Transaction Library illustrates the accounting entries for USSGL budgetary and proprietary accounts. Both are updated on an annual basis at a minimum. Refer to the Standard Financial Information Structure given in subparagraph 1.3.3 for a decomposition of DoD USSGL accounting transactions for DWCF reimbursement and revenue recognition.
`;

export const FMR_V11B_CH11_CONTENT = `
VOLUME 11B, CHAPTER 11: “REIMBURSEMENTS AND REVENUE RECOGNITION - DEFENSE WORKING CAPITAL FUNDS”

SUMMARY OF MAJOR CHANGES
Changes are identified in this table and also denoted by blue font.
Substantive revisions are denoted by an asterisk (*) symbol preceding the section, paragraph, table, or figure that includes the revision.
Unless otherwise noted, chapters referenced are contained in this volume.
Hyperlinks are denoted by bold, italic, blue, and underlined font.
The previous version dated October 2002 is archived.

PARAGRAPH EXPLANATION OF CHANGE/REVISION PURPOSE
Chapter Title
Modified the Chapter title from “Reimbursements And Revenue Recognition” to “Reimbursements and Revenue Recognition - Defense Working Capital Funds.” This aligns with the titles used for Chapters 1 - 3. It also distinguishes the Chapter from Volume 11A during online searches.
Revision

1.0 (1101)
Revised the “General” section and added “Overview”, “Purpose” and “Authoritative Guidance” paragraphs in order to comply with the DoD Financial Management Regulation Standard Operating Procedures.
Revision

2.4 (110204)
Updated guidance for use of Project Orders in accordance with Title 41, United States Code, section 6307 (41 U.S.C. § 6307) and for usage of Economy Act Orders in accordance with 31 U.S.C. § 1535.
Revision

2.5 (110205) 
Updated guidance for work performed per 10 U.S.C. § 127a. 
Revision

2.6 (110206)
Updated guidance for Work Performed in Advance of Reimbursable Orders in accordance with the Office of Management and Budget Circular A-11.
Revision

2.8 (110208)
Updated requirements for stabilized rates to align with Volume 2B, Chapter 9. 
Revision

3.1 (110301)
Updated guidance for recognizing and reporting revenue in accordance with Federal Accounting Standards Advisory Board, Statement of Federal Financial Accounting Standards 7, and relevant portions of the Deputy Chief Financial Officer Memorandum, “Policy Change to Account for In Transit Inventory Assets (FPM 19-10),” dated December 9, 2019.
Revision

3.2 (110302)
Updated guidance on Service Type and End-Product Type Orders. 
Revision

3.4 (110304)
Removed the budgetary and proprietary accounting entries provided in the former section 3.0 and referred users to the DoD U.S. Standard General Ledger Transaction Library.
Revision

4.0 (1104)
Removed the Prior Period Adjustment content provided in the former section 4.0 because this guidance is given in Volume 4, Chapter 17.
Deletion

CHAPTER 11
REIMBURSEMENTS AND REVENUE RECOGNITION - DEFENSE WORKING CAPITAL FUNDS

1.0 GENERAL (1101)

1.1 Overview (110101)
Reimbursements are collections earned for selling goods or providing services. Reimbursable obligations are obligations financed by offsetting collections credited to an expenditure account in payment for goods and services provided by that account. The collection must be authorized by law to credit the specific appropriation or fund account. The Under Secretary of Defense (Comptroller) must authorize reimbursable authority through budget formulation in Annual Operating Budgets and statutory authorization in the annual National Defense Authorization Act. Refer to Volume 3, Chapter 15 for additional information relating to the standards for recording the receipt and distribution of budgetary resources in execution-level activities.

1.2 Purpose (110102)
This chapter establishes guidance for reimbursements and revenue recognition for the DoD Defense Working Capital Fund (DWCF).

1.3 Authoritative Guidance (110103)
The accounting policy and related requirements prescribed in this chapter are in accordance with the applicable provision of:
1.3.1. Federal Accounting Standards Advisory Board, Statement of Federal Financial Accounting Standards 7 (SFFAS 7) “Accounting for Revenue and Other Financing Sources and Concepts for Reconciling Budgetary and Financial Accounting.”
1.3.2. Office of Management and Budget (OMB) Circular A-11 “Preparation, Submission, and Execution of the Budget.”
1.3.3. Standard Financial Information Structure. “DoD Standard Reporting Chart of Accounts and DoD U.S. Standard General Ledger (USSGL) Transaction Library.”
1.3.4. Title 10, United States Code, section 127a (10 U.S.C. § 127a) “Operations for which Funds Are Not Provided In Advance: Funding Mechanisms,” 10 U.S.C. § 2208 “Working-capital Funds,” 10 U.S.C. § 2210 “Proceeds of sales of supplies: credit to appropriations,” and 10 U.S.C. § 2563 “Articles and Services of Industrial Facilities: Sale to Persons Outside the Department of Defense.”
1.3.5. U.S. Department of the Treasury (Treasury), Bureau of the Fiscal Service, Federal Account Symbols and Titles (FAST Book).

2.0 REIMBURSEMENTS (1102)

2.1 Reimbursement Principles (110201)
2.1.1. 10 U.S.C. §§ 2208 and 2210 provide the basic transactional authority for the DWCF. These authorize the Secretary of Defense to finance inventories of supplies, industrial-type activities, and commercial-type activities that provide common services within or among activities of the DoD. Supply-type services involve the sale of material financed using contract authority established by 10 U.S.C. § 2210(b) subsequently liquidated using revenue earned and collected from sales. Industrial-type services may be financed for requirements internal to a military department or for external customers and commercial-type activities may be financed for requirements within or among the departments and agencies that comprise the DoD. As required by 10 U.S.C. § 2208(o), charges for goods and services provided through a DWCF activity must include amounts to recover the full costs of goods and services provided and amounts for capital investment recovery.
2.1.2. The DWCF billings to and reimbursements from ordering activities for services or goods provided must be accomplished in the most efficient and expeditious manner available to reduce or eliminate the need for additional DoD working capital. In addition, the nature of the DWCF requires ordering activities to budget, control, and account for the cost of all goods and services ordered (refer to 10 U.S.C. § 2208).
2.1.3. As a result, a DWCF activity:
2.1.3.1. Must bill ordering activities for all costs incurred as a result of an accepted customer order as long as the billings does not exceed the fixed-price contract amount.
2.1.3.2. Must bill customer order cancellation or reduction costs. When a job order is canceled or reduced in scope after a DWCF activity has commenced work or incurred costs on the order, the costs incurred, plus the applied overhead (that is, indirect and other normally allocated overhead, such as General and Administrative (G&A) costs) plus costs associated with the cancellation or reduction must be charged to the customer. Examples of directly associated cancellation or reduction costs to be charged to customers are advance planning costs, non-creditable direct materiel, special test equipment, necessary preservation and/or shipment effort, and any additional effort necessitated by the cancellation and/or reduction; for example, salvaging of materiel. In addition, costs charged to customers should include the costs of salaries payable to employees hired specifically to work on the canceled order until the employees are, or could have been, separated through a reduction in force or other appropriate action (taking into account appropriate administrative lead time), or reassigned to other direct jobs. Materiel is defined as all items necessary to equip, operate, maintain, and support military activities without distinction as to their application for administrative or combat purposes, excluding real property, installations, and utilities. Materiel is either serviceable (i.e., in an issuable condition) or unserviceable (i.e., in need of repair to make it serviceable). This definition is taken from DoD Instruction 4140.01 “DoD Supply Chain Materiel Management Policy.”
2.1.3.3. Must not charge the customer for costs that are indirectly associated with cancellation or reduction actions. For example, do not charge a customer canceling or reducing an order for under-applied indirect production and G&A overhead costs that result from a reduced workload base of the DWCF activity as a whole. Instead, record the under-applied costs against the net operating results of the performing DWCF activity.
2.1.3.4. Must not enter into any arrangement to offset services/materials received and services/materials furnished, except for Foreign Military Sales (FMS)/Foreign Exchange Agreements as provided in Volume 15 or via Acquisition and Cross-Servicing Agreements as provided in Volume 11A, Chapter 8.

2.2 Reimbursable Orders (110202)
2.2.1. No work or service should be performed by a DWCF activity except on the basis of reimbursable orders received and accepted that constitute obligations of Federal Government ordering activities or cash advances from non-Federal Government entities. Direct fund cite orders will include a reimbursable order portion for the applicable DWCF overhead rate. Economy Act Orders may be issued as direct fund cite orders where the ordering activity identifies the appropriate fund citation for the servicing activity to place on the reimbursable order (refer to Volume 11A, Chapter 3).
2.2.2. Each DWCF activity must record promptly all orders accepted and must account continuously for the status of all orders in terms of deliveries, billings, and unfilled balances. This will provide a basis for scheduling production or operations, assessing work backlogs, determining the need for additional orders or to reduce activity, preparing operating budgets and forecasts, and promptly informing customers about changes in delivery schedules.

2.3 Basis for Reimbursement (110203)
2.3.1. All orders accepted by a DWCF activity must be in writing (either on paper or an electronic document); for a purpose authorized by law; executed before cancellation of the issuing appropriation; and must call for specific goods, real property, work, or services. The DWCF activity will adhere to the accounting standards hierarchy in Volume 1, Chapter 2 in accepting, recording, billing and reporting reimbursable activities.
2.3.2. Each Project Order or other order accepted by a DWCF activity must state specifically the basis of reimbursement to the DWCF for the cost of work or services ordered, as between fixed-price or cost reimbursement. For DWCF industrial facility sales to persons outside the DoD under authority of 10 U.S.C. § 2563, materials or services may be sold on either a fixed-price or cost reimbursement basis.
2.3.3. Orders from the public, including State, local and foreign governments must be accompanied by an advance because DWCF activities cannot recognize budgetary resources for a non-Federal order until a receipt is collected. Volume 4, Chapter 3 provides an exception for fuel sales to the public. According to Chapter 1, paragraph 010208, cash advances may also be requested from Federal Government activities when directed and approved in advance by the Office of the Under Secretary of Defense (Comptroller) (OUSD(C)).

2.4 Performance Under Project Orders and Economy Act Orders (110204)
A performing activity’s mission, function and the nature of the transaction will determine whether 10 U.S.C. § 2208 or another statutory authority governs a class of orders. As stated in subparagraph 2.1.1, 10 U.S.C. § 2208 is the primary transactional authority for DWCF sales of materials and for the provision of services by chartered DWCF industrial and commercial activities that provide common services within or among DoD components. The Economy Act and the Project Order Statute are additional statutes that may pertain to some DWCF sale transactions.
2.4.1. The DoD Components (i.e., DoD-owned and operated activities) ordering work or services from a DWCF financed activity may place a Project Order whenever such an order meets the requirements for Project Orders established in Volume 11A, Chapter 2. A DWCF customer with a qualifying requirement would use authority conferred by 41 U.S.C § 6307 to account for the obligation in the same manner as it would a procurement contract for a similar requirement with commercial manufacturer or private contractor. To qualify as a Project Order under policy in Volume 11A, Chapter 2 the customer request must be a bonafide need of the fiscal year (FY) in which the Project Order is placed. DWCF customers may place Project Orders only for non-severable requirements that are performed over a period of time which may cross a FY.
2.4.2. Organizations financed by the DWCF accept and perform orders within the scope of their DWCF charter mission under transactional authority conferred by 10 U.S.C. § 2208. Such organizations may also accept and perform Economy Act Orders under 31 U.S.C. § 1535, when providing intra-DoD or intragovernmental support not falling within the activity’s DWCF charter mission, provided they otherwise meet the criteria of such orders as described in Volume 11A, Chapter 3. For instance, when a tenant of a DWCF-financed activity reimburses a DWCF installation host, the Economy Act governs the transaction. Such support would not involve provision of supplies or common services for which the DWCF-financed activity was chartered. Support categories for which the Economy Act may provide transaction authority include, but are not limited to, base support (host-tenant) services, civilian personnel services, community services, environmental compliance, fire protection, food service, health service, mail service, police service, security/guard services, and warehousing.
2.4.3. The customer order and funding document should identify the applicable statutory authority (i.e., Project Orders, Economy Act Orders, or 10 U.S.C. § 2208) upon acceptance by the performing activity. See Treasury’s Bureau of the Fiscal Service, Interagency Agreement, United States Government Order Instructions, FS Form 7600B. The requesting and servicing activities must identify the applicable statutory and program authorities. FS Form 7600B allows for this information to be provided in blocks 17-19 and 20-21, respectively.

2.5 Reimbursement for Contingency Operations and Humanitarian Efforts (110205)
2.5.1. All DWCF activity groups, including transportation services provided by the U.S. Transportation Command (USTRANSCOM), operate on a reimbursement basis with users paying for goods and services provided. Payment for contingency operations, including deployment or other emergency response for military or humanitarian assistance, is no exception.
2.5.2. The Military Department Headquarters is responsible for determining which level within the Military Department will pay (that is, at the unit, major command, or Military Department-level). This process also applies when a Unified Combatant Command tasks a Service-funded unit to perform a mission (such as transportation of military personnel or equipment by the USTRANSCOM). Payment for the services provided is the responsibility of the Military Department controlling the equipment or personnel receiving the service.
2.5.3. Transportation provided in response to a Request for Assistance (RFA) from another government agency must not result in third party collections. The Military Department that controls the equipment or personnel being transported is responsible for reimbursing USTRANSCOM. It is the responsibility of the Military Department that accepted the RFA to collect any required reimbursements owed to that Military Department by the requesting government agency.
2.5.4. An exception to this policy occurs when the USTRANSCOM receives an order from the Joint Chiefs of Staff requiring transportation of non-U.S. owned equipment and/or non-U.S. personnel such as unreimbursed efforts in support of the United Nations. In those instances, the Army will pay Surface Deployment and Distribution Command costs, the Navy will pay Military Sealift Command costs, and the Air Force will pay Air Mobility Command costs. Bills may be centralized for more convenient processing if appropriate; however, billings must be forwarded to the appropriate Military Department within 30 days from commencement of the contingency operation or humanitarian effort. The Military Departments must pay these bills, including transportation costs, in a timely manner.
2.5.5. Authority for another exception to this policy is available for operations described in 10 U.S.C. § 127a. 10 U.S.C. § 127a does not confer authority to conduct operations, but rather establishes mechanisms by which funds are provided for two types of operations that the armed forces are required to carry out under some other authority in the absence of advance funding. The first involves the deployment (other than for a training exercise) of elements of the armed forces. The second involves the provision of humanitarian assistance, disaster relief, or support for law enforcement (including immigration control). 10 U.S.C. § 127a(b) authorizes the Secretary of Defense to not require reimbursement for specified services rendered by DWCF activities to a unit of the armed forces performing a section 127a mission.

2.6 Work Performed in Advance of a Reimbursable Order (110206)
In certain situations, work for customers may begin in advance of receipt and acceptance of a formal order. They are as follows:
2.6.1. In periods under which the Department is operating under a Continuing Resolution (CR). For more details, refer to Volume 3, Chapter 2 and OMB Circular A-11, Section 123. Orders issued under a CR must identify the portion covered by current obligational authority. When obligational authority is not available neither work nor service is to be performed. Another option is to request that OMB provide an exception apportionment. This must include a written justification that provides the legal basis for the request.
2.6.2. When it is necessary, in an urgent situation, to incur limited costs in advance of the receipt of a regular order for an authorized program for which customer funds are available, such work or services may be undertaken on the basis of a letter of intent which constitutes an obligation of the ordering activity in a stated amount sufficient to cover the advance costs that may be incurred. Therefore, letters of intent are obligating instruments, contractual in nature, and must be funded upon issuance. A letter of intent must expire within 30 days from the date of issuance.
2.6.3. When it is necessary to begin work of an emergency nature prior to the receipt of an order, a commanding officer’s order or similar order may be issued by the commander of the DWCF activity subject to the following conditions:
2.6.3.1. The DWCF activity must have written assurance that an order must be issued promptly or must have equivalent documented communication. The use of such orders must be limited to situations in which there are bona fide emergencies arising from unforeseen urgent requirements, e.g., loss or damage caused by a disaster, an act of God, or events caused by unforeseen security situations. A commanding officer’s order must not be used as a normal procedure to circumvent administrative lead-times that should be considered in advance planning.
2.6.3.2. A commanding officer’s order must expire within 30 days from the date of issuance.
2.6.3.3. A commanding officer’s order must be issued on a local form (e.g., DoD (DD) Form 577, Appointment/Termination Record - Authorized Signature) and must be approved and signed by the commanding officer or an authorized representative.

2.7 Follow-up on Unfunded Reimbursable Orders (110207)
While there may be some services furnished by a DWCF activity prior to receiving a funded order, this should be a rare occurrence. Whenever this occurs, these services are performed on the basis of anticipated orders or for programs included in approved budget requests. This type of work is for existing customers that have annual recurring requirements. However, when items are furnished or services performed in response to an unfunded reimbursable order (express or implied), and a funded order has not been submitted after 15 days of providing the service, the DWCF organization must notify the comptroller of the customer organization and request a funded order. If funding is not received within 30 days of providing the service, the DWCF organization must notify the OUSD(C), Deputy Comptroller Program/Budget (P/B) - Revolving Funds Directorate, and request authorization to directly bill the customer’s appropriation account. The OUSD(C) P/B - Revolving Funds Directorate must respond to the request within 15 days. Upon authorization by the OUSD(C) P/B - Revolving Funds Directorate, the DWCF organization will self-reimburse the DWCF, citing the customer’s appropriation.

2.8 Billing Standard (110208)
The DWCF Components performing work or services on a customer order must bill the requesting DoD Component, other Federal agency, or the public for earned reimbursements (performance of work or services, payments to contractors, or delivery from inventory) within 30 calendar days after the month in which performance occurred. The payment due date must not be more than 30 calendar days from the date of the invoice.
2.8.1. Stabilized rates must be established to achieve an Accumulated Operating Result (AOR) of zero in the budget year. This means the stabilized rates must recover operating expenses estimated to be incurred for the applicable FY and provide sufficient working capital for the acquisition of fixed assets as approved by the OUSD(C) P/B - Revolving Funds Directorate. Therefore, stabilized rates and unit prices must be established at levels intended to provide for estimated revenues to equal estimated costs plus approved surcharges for the applicable FY for which the rates and unit prices are established. In budget execution, activities will incur either a positive or a negative operating result. Accordingly, activities will increase their budget year prices to make up actual or projected losses of budgetary resources or reduce their budget year prices to return actual excess resources or projected budgetary gains to customers. Activities may request recovery of AOR outside the budget year in instances when an AOR of zero cannot be achieved. This request must be included in the budget submission and approved by the OUSD(C) P/B - Revolving Funds Directorate. Refer to Volume 2B, Chapter 9 for specific details.
2.8.2. When established stabilized rates and unit prices are insufficient to cover the increase in actual costs incurred for Project Order or Economy Act Order cost reimbursable orders, renegotiations in the current FY need not be conducted for small dollar amounts ($0.01 to $2,500.00) when the probable cost of renegotiation is greater than the adjustment amount. The resulting negative operating result must be addressed to achieve an AOR of zero in the budget year in accordance with the guidelines in subparagraph 2.8.1.
2.8.3. Private parties and concerns, when authorized by law including foreign governments, and state and local governments must reimburse the DWCF for the full costs incurred by the Federal Government. Full costs for foreign military, state and local government, and private party sales must include unfunded costs that are not charged to the DoD or other Federal Government customers (such as unfunded civilian retirement and postretirement health benefits costs). Amounts collected for unfunded civilian retirement and postretirement health benefits costs must not be retained by DWCF activities; rather, such amounts must be deposited into either the Miscellaneous Receipts Account 3210, “General Fund Proprietary Receipts, Defense Military, Not Otherwise Classified,” or for FMS into Account 3041, “Recoveries Under the Foreign Military Sales Program, Army, Navy, Air Force, Defense” (see the FAST Book). Volume 15, Chapter 7 provides additional information on the determination of full costs for FMS.

2.9 Disputed Bills between DoD Components (110209)
2.9.1. Payment for ordered goods and services must be made promptly after the receipt of the bill/invoice by the requesting activity from the performing activity. Payment may be in advance or on providing the goods or services ordered and must be for any part of estimated or actual cost as determined by the activity filling the order. Proper adjustment of amounts paid in advance must be made as agreed to by the ordering and performing activities on the basis of the goods or services provided. A bill submitted or a request for payment must be paid promptly and not postponed subject to audit or other similar validation in advance of payment. This provision is not intended to preclude questions on the accuracy and correctness of the billed amounts but is intended to preclude the nonpayment of bills subject to the resolution of disputed billing details. Every effort must be expended to resolve disputed billing details within 60 days. The billing activity may request adjudication from the OUSD(C) P/B - Revolving Funds Directorate if, after 60 days, agreement as to the resolution of billing details cannot be reached. The OUSD(C) P/B - Revolving Funds Directorate must provide a decision on disputed bills within 30 days.
2.9.2. The providing activity may request approval from the OUSD(C) P/B - Revolving Funds Directorate to collect from the customer such amounts as are unpaid, in cases where there is a question as to ownership of the bill (vice dispute over the amount of the bill or other billing details), and the bill remains unpaid for more than 90 days. The OUSD(C) P/B - Revolving Funds Directorate must provide a decision on ownership questions within 30 days.

3.0 REVENUE RECOGNITION (1103)

3.1 Reporting Requirements (110301)
3.1.1. DoD Components must use the percentage of completion method for recognizing revenue on all customer orders. Under this method, the revenue earned on an order must be recognized, based on the ratio that costs of goods incurred and services provided to date, bear to the total costs estimated to be incurred on the order when it is completed (see SFFAS 7, paragraph 149 for guidance and exceptions to this treatment). The completed contract method for revenue recognition is not an acceptable method for recognizing revenue within the Department.
3.1.2. Revenue and costs must be recognized in the same accounting period. In accordance with SFFAS 7, paragraph 36(c), “when goods are kept in inventory so that they are available to customers when ordered, revenue should be recognized when the goods are delivered to the customer.” This is clarified in the OUSD(C) Financial Management Regulation Policy Memorandum (FPM) 19-10 “Policy Change to Account for In-Transit Inventory Assets” dated December 9, 2019. According to FPM 19-10 revenue recognition must occur at the point of receipt of the inventory by the customer effective FY 2021. Volume 4, Chapter 17, subparagraph 170506.A provides that DWCF activities routinely post operating expenses/program costs to a Cost of Goods Sold (COGS) account (either directly to Operating Expenses/Program Costs or via Work-in-Process accounts) so that costs may be matched to revenue upon completion of the task or filling an order. A standard policy for recognizing and reporting revenue must apply for all activities within a DWCF activity group. The amount of revenue recognized must not exceed the amount specified in the order.
3.1.3. Activities in the DWCF industrial activity groups must use a work-in-process account to capture and hold inventory costs prior to their recognition as a COGS. Examples of chartered DWCF industrial activities include the Army Industrial Operations Activity Group, Navy Depot Maintenance Activity Group, and Air Force Consolidated Sustainment Activity Group-Maintenance Division’s depots. DWCF industrial activities are chartered activities with primary missions involving depot maintenance, transportation, and research and development (refer to Volume 2B, Chapter 9).
3.1.4. Activities in the Transportation commercial activity group must recognize revenue based upon receipt of a cargo manifest, the commencement of travel or the agreed upon shipping terms.
3.1.5. Activities in Supply Management activity groups must not recognize revenue, and costs of goods sold, and should not reduce their inventory financial balance until receipt by the customer occurs. This is because materiel does not transfer from the DWCF supply management activity’s inventory until receipt of the materiel by the customer. Therefore, if billing and collection happen prior to receipt by the customer, the funds received by the DWCF must be recorded as an unearned revenue liability. Billing or collection by Supply Management activity groups at time of shipment is not an advance billing under 10 U.S.C. § 2208(l). Upon confirmation of receipt, the DWCF will recognize revenue earned, relieve the liability, reduce inventory, and recognize COGS.
3.1.6. The customers of supply, industrial and commercial activities financed using DWCFs must record complementary accounting entries. Payment prior to receipt of materiel must be recorded as an advance payment, with a corresponding credit to Fund Balance with Treasury. Upon receipt of the materiel, the customer will relieve the advance and debit either an appropriate asset account (e.g., Operating Materials and Supplies held for use) or recognize an expense, if applicable.
3.1.7. Both the DWCF and the customer must also make or adjust any budgetary accounting entries to maintain Treasury Tie-Points. Tie-Points, also referred to as Tie-Point Reconciliations, are a series of standard USSGL accounting relationships that indicate whether certain account balances within a general ledger trial balance are consistent with other account balances. Tie-Points facilitate the validation of trial balance data. Refer to Volume 1, Chapter 7 and the Standard Financial Information Structure given at 1.3.3 for details.
3.1.8. Activities in the Commissary Resale activity group must recognize revenue, and related costs, at the point/time of sale.
3.1.9. In the event that a service is rendered, revenue must be considered earned, and recognized, and associated costs must be reported, at the time that the service is rendered/performed, but not less frequently than monthly on the last calendar day.
3.1.10. Activities in Navy Research and Development activity group must use the percentage of completion method for revenue recognition for production type (end-product item) orders, or report revenue as actual costs are incurred and billed for service type orders.
3.1.11. Activities in all other industrial or commercial activity groups (for example, Financial Operations, Base Support, Information Services, Reutilization and Marketing, and Printing and Publications) not discussed in subparagraphs 3.1.1 through 3.1.10, must recognize revenue and the associated costs, when it is earned. In other words, at the time that the service is rendered/performed, but not less frequently than monthly on the last calendar day.

3.2 Service Type Orders versus End-Product Type Orders (110302)
3.2.1. For service type orders, a work-in-process account must not be used to capture and hold costs. According to SFFAS 7, paragraph 36(a), revenue should be recognized when the services are performed. Consequently, service type orders must be considered as rendered/completed, and revenue and costs periodically recognized, at least on the last day of the month. Descriptions of projects and work that should be classified as service type orders include:
3.2.1.1. Research and Development includes the conduct and support of research, development, test, and evaluation; basic research; applied research; advanced technology development; advanced component development and prototypes; system development and demonstration; and developmental engineering. Does not include production of items for service testing or engineer-user testing. The Navy’s Warfare Centers and Laboratories are examples of DWCF activities that perform these types of orders.
3.2.1.2. Transportation Services includes transportation (air, land, and sea) services such as the movement of supplies and provisions to deployed forces. This includes operation of ports, port facilities and related sub-installations, passenger trans-shipment activities, and air refueling. This also includes the operation of docks, piers, terminals or similar facilities; and wharfage, ferrying, lighterage and stevedoring. The Navy Military Sealift Command performs these types of orders.
3.2.1.3. Communication and Information Services includes telecommunication services and data processing services (other than those services addressed in subparagraph 3.2.1.5) rendered. For example, the Defense Information Systems Agency operates the information services activity within the DWCF. This activity consists of two main components. The first component includes two lines of service, telecommunications services and enterprise acquisition services. The second component includes computing services.
3.2.1.4. Specialized Commercial Services. The Defense Counterintelligence and Security Agency’s personnel vetting program provides personnel background investigations on a fee-for-service basis. The Defense Finance and Accounting Service provides debt management and payment services; payroll services for military personnel, retirees, annuitants and civilians; and performs accounting and reporting for customers that place service type orders.
3.2.1.5. Technical Information includes central collection and dissemination for DoD technology based information. Includes provision of access to, and transfer of, scientific and technical information. Also includes provision of computer modeling, data services, and response to requests for solutions to technological problems of the Military Departments.
3.2.1.6. Printing Services includes printing, reproduction and document automation, workflow conversion, electronic storage and output, multi-function devices, office printers, and distribution of hard copy and digital information. The Defense Logistics Agency is an example of an activity that provides these services.
3.2.1.7. Distribution Depots includes management and procurement of items with a designated national stock number for all DoD customers. For example, the Army’s Industrial Operations activity group conducts depot level maintenance, repair and upgrade; produce munitions and large caliber weapons; and store, maintain, and demilitarize materiel for all branches of DoD.
3.2.1.8. Supply Management services involving receipt, reclamation, storage, and issue of consumables and reparable items. For example, the Army DWCF Supply Management activity group administers spare parts inventory for Army managed items, Non-Army managed items and war reserve secondary items. The activity also maintains a protected inventory of spares in Army Prepositioned Stocks, which is released to support deploying combat units.
3.2.1.9. Contract Management includes expediting the products and services delivered by industry, assuring that the specifications of the contract are met and paying contractor invoices for these items. Also includes surveillance of contractor operations to assure compliance with contractual requirements and determining the effectiveness of contractor quality control systems and inspection procedures, and officially accepting materiel on behalf of the government after certifying its conformance to contract provisions. Also includes provision of on-site assistance to program managers, such as representation and participation in meetings and informal program/contract reviews.
3.2.1.10. Base Support includes facilities maintenance, family housing services, other housekeeping services, and administrative functions, provided to tenants and others. Also includes provision of utility services (central heat and power, electricity, water, wastewater disposal, and natural gas).
3.2.1.11. Engineering Services includes provision of technical and engineering assistance in matters relating to various weapon systems, industrial plant equipment, and associate system when they do not relate to research and development projects. Also includes repair service and quality evaluation; that is, inspecting, calibrating, testing, evaluating, trimming and reengineering of items. For example, the Air Force enhances readiness by efficiently and economically repairing, overhauling and modifying aircraft, engines, missiles, components, and software to meet customer demands through its Consolidated Sustainment Activity Group-Maintenance Division.
3.2.1.12. Support of Reserve (Under and Unutilized) Capacity includes maintenance of unutilized capacity and support of underutilized capacity.
3.2.1.13. Commissary Services includes operation of Defense commissaries. Also includes provision of troop issue subsistence and programming of the replacement of War Reserve Materiel rotation rations. For example, the Defense Commissary Agency collects revenues from product sales in commissary stores through its Resale Stocks business activity.
3.2.1.14. Reutilization and Marketing Service includes the reuse of excess and surplus property within the Federal Government and other authorized agencies, donation to local governments, and the sale of the remaining property to the public on a competitive basis.

3.2.2. A work-in-process account must be used to capture and hold costs prior to their recognition as a COGS that will support revenue recognition. Descriptions of applicable projects and work that should be classified as end-product type orders are as follows:
3.2.2.1. Overhaul or a complete rebuilding of parts, assemblies, subassemblies, and end-items.
3.2.2.2. Manufacture and Assembly such as furnishing customers with new end-items and components. In addition, manufacturing prototypes or furnishing items to the customer for testing.
3.2.2.3. Ordnance is defined as explosives, chemicals, pyrotechnics, and similar stores, e.g., bombs, guns and ammunition, flares, smoke, or napalm. Refer to the DoD Dictionary of Military and Associated Terms. This type order includes the receipt, segregation, demilitarization, storage, assembly, disassembly, test, maintenance, and issuance actions.
3.2.2.4. Construction and Conversion includes construction and conversion of property and equipment.
3.2.2.5. Alteration and Modification includes alteration and modification of property and equipment.
3.2.2.6. Other Products include products not otherwise classified such as the production of research and development items for service testing or engineer-user testing.
`;
